[build]

builder = "dockerfile"
dockerfilePath = "/docker/Dockerfile"

# builder = "nixpacks"
# buildCommand = "npm i && npm run build:web"


[deploy]
startCommand = "npm run prisma:migrate-deploy && npm run dev"
